---
- name: Update Arch package database
  pacman:
    update_cache: yes
  become: true

- name: Install Arch-specific packages
  pacman:
    name: "{{ arch_packages + modern_cli_packages }}"
    state: present
  become: true

- name: Check if paru is installed
  command: which paru
  register: paru_check
  failed_when: false
  changed_when: false

- name: Install paru (AUR helper) if not present
  block:
    - name: Clone paru repository
      git:
        repo: https://aur.archlinux.org/paru.git
        dest: /tmp/paru
      when: paru_check.rc != 0
    
    - name: Build and install paru
      shell: cd /tmp/paru && makepkg -si --noconfirm
      when: paru_check.rc != 0
  when: paru_check.rc != 0

- name: Install AUR packages
  command: paru -S --noconfirm {{ aur_item }}
  loop: "{{ aur_packages }}"
  loop_control:
    loop_var: aur_item
  when: aur_packages is defined
