---
- name: Include OS-specific variables
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_facts['distribution'] | lower }}.yml"
    - "{{ ansible_facts['os_family'] | lower }}.yml"
    - "default.yml"

- name: Include OS-specific tasks
  include_tasks: "{{ item }}"
  with_first_found:
    - "{{ ansible_facts['distribution'] | lower }}.yml"
    - "{{ ansible_facts['os_family'] | lower }}.yml"
    - "generic.yml"

- name: Install common packages
  package:
    name: "{{ common_packages }}"
    state: present
  become: true

- name: Configure SSH
  block:
    - name: Create SSH directory
      file:
        path: ~/.ssh
        state: directory
        mode: '0700'

    - name: Install OpenSSH server
      package:
        name: openssh
        state: present
      become: true

    - name: Enable and start SSH service
      systemd:
        name: sshd
        enabled: yes
        state: started
      become: true

    - name: Open SSH firewall port with UFW
      ufw:
        rule: allow
        port: 22
        proto: tcp
        comment: "SSH access for remote management"
      become: true
