---
- name: Include OS-specific variables
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_facts['distribution'] | lower }}.yml"
    - "{{ ansible_facts['os_family'] | lower }}.yml"
    - "default.yml"

- name: Include OS-specific tasks
  include_tasks: "{{ item }}"
  with_first_found:
    - "{{ ansible_facts['distribution'] | lower }}.yml"
    - "{{ ansible_facts['os_family'] | lower }}.yml"
    - "generic.yml"

- name: Install common packages
  package:
    name: "{{ common_packages }}"
    state: present
  become: true

- name: Configure SSH
  block:
    - name: Create SSH directory
      file:
        path: ~/.ssh
        state: directory
        mode: '0700'

    - name: Create SSH config
      template:
        src: ssh_config.j2
        dest: ~/.ssh/config
        mode: '0600'
      when: not ansible_check_mode
