---
development_packages:
  - python
  - python-pip
  - python-pipx
  - nodejs
  - npm
  - yarn
  - go
  - rust
  - ansible
  - terraform
  # pandoc removed - pulls in 200+ Haskell dependencies
  # Use pandoc-bin from AUR or install on-demand if needed

dev_aur_packages:
  - ollama
  - trufflehog

# Go tools installed via go install
go_tools: []
  # Add go tools here as needed, e.g.:
  # - github.com/some/tool@latest
