---
- name: Install Distrobox dependencies
  package:
    name: "{{ distrobox_deps }}"
    state: present
  become: true

- name: Install Distrobox
  block:
    - name: Check if Distrobox is installed
      command: which distrobox
      register: distrobox_check
      failed_when: false
      changed_when: false
    
    - name: Download Distrobox installer
      get_url:
        url: https://raw.githubusercontent.com/89luca89/distrobox/main/install
        dest: /tmp/distrobox-install
        mode: '0755'
      when: distrobox_check.rc != 0
    
    - name: Install Distrobox
      command: /tmp/distrobox-install
      when: distrobox_check.rc != 0

- name: Create development container
  command: >
    distrobox create 
    --name {{ dev_container_name }} 
    --image {{ dev_container_image }}
    {% if gpu_type == 'nvidia' %}--nvidia{% endif %}
  args:
    creates: "~/.local/share/containers/storage/overlay-containers/{{ dev_container_name }}"

- name: Ensure modular bash config directory exists
  file:
    path: ~/.config/bash
    state: directory
    mode: '0755'

- name: Setup environment variables in exports.sh
  blockinfile:
    path: ~/.config/bash/exports.sh
    marker: "# {mark} ANSIBLE MANAGED BLOCK - ARCFORGE ENV VARS"
    create: yes
    mode: '0644'
    block: |
      # Arcforge environment setup
      export AUTO_DEV_ENV={{ auto_enter_dev_env | default('false') }}
      {% if work_environment | default(false) %}
      export WORK_ENVIRONMENT=true
      {% else %}
      export WORK_ENVIRONMENT=false
      {% endif %}

- name: Configure container auto-entry in work.sh
  blockinfile:
    path: ~/.config/bash/work.sh
    marker: "# {mark} ANSIBLE MANAGED BLOCK - ARCFORGE DISTROBOX"
    create: yes
    mode: '0644'
    block: |
      # Auto-enter development container (managed by Arcforge)
      if [[ -z "$CONTAINER_ID" && "$TERM" != "dumb" && -z "$SSH_CONNECTION" && -t 1 && "$AUTO_DEV_ENV" == "true" ]]; then
        exec distrobox enter {{ dev_container_name }}
      fi

- name: Ensure ~/.bashrc uses modular config structure
  copy:
    dest: ~/.bashrc
    mode: '0644'
    backup: yes
    content: |
      #
      # ~/.bashrc
      #

      # If not running interactively, don't do anything
      [[ $- != *i* ]] && return

      # Load modular configs
      for config in ~/.config/bash/*.sh; do
          [[ -r "$config" ]] && source "$config"
      done
    force: no
