all:
  children:
    personal:
      hosts:
        workstation:
          ansible_host: localhost
          ansible_connection: local
          os_family: arch
          machine_type: workstation
          gpu_type: nvidia
        personal-laptop:
          ansible_host: localhost
          ansible_connection: local
          os_family: ubuntu
          machine_type: laptop
          gpu_type: hybrid
    work:
      hosts:
        work-laptop:
          ansible_host: localhost
          ansible_connection: local
          os_family: ubuntu
          machine_type: laptop
          gpu_type: hybrid
