---
- name: Setup base system
  hosts: all
  roles:
    - role: base
    - role: fonts
    - role: shell/bash
    - role: development/tools

- name: Setup workstation (rhl-kaine)
  hosts: rhl-kaine
  roles:
    - role: desktop/applications/terminal
    - role: desktop/applications/utilities
    - role: gpu/nvidia

- name: Setup personal laptop
  hosts: personal_laptop
  roles:
    - role: desktop/tiling_wm/hyprland
      when: install_hyprland | default(false)
    - role: desktop/applications/terminal
    - role: desktop/applications/utilities
    - role: gpu/hybrid
    - role: development/containers
      vars:
        auto_enter_dev_env: true
        dev_container_name: dev
        dev_container_image: archlinux:latest

- name: Setup work laptop  
  hosts: work_laptop
  roles:
    - role: desktop/tiling_wm/hyprland
      when: install_hyprland | default(false)
    - role: desktop/applications/terminal
    - role: desktop/applications/utilities
    - role: gpu/hybrid
    - role: development/containers
      vars:
        auto_enter_dev_env: false
        work_environment: true
        dev_container_name: dev
        dev_container_image: archlinux:latest
