---
- name: Install bash packages
  package:
    name: "{{ bash_packages }}"
    state: present
  become: true

- name: Install AUR bash packages
  command: paru -S --noconfirm {{ item }}
  loop: "{{ bash_aur_packages }}"
  when: ansible_facts['os_family'] == "Archlinux"

- name: Configure starship prompt
  block:
    - name: Create config directory
      file:
        path: ~/.config
        state: directory
        mode: '0755'
    
