---
ubuntu_packages:
  - build-essential
  - git
  - vim
  - neovim
  - tmux
  - htop
  - wget
  - curl
  - rsync
  - zip
  - unzip
  - python3
  - python3-pip
  - ripgrep
  - fd-find
  - fzf
  - openssh-client

ubuntu_ppas:
  - ppa:neovim-ppa/unstable

common_packages:
  - man-db
  - manpages
  - which
  - grep
  - sed
  - gawk
  - bash-completion
